quarkus:
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER:quarkus}
    password: ${POSTGRES_PASSWORD:quarkus}
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://db:5432/${POSTGRES_DB:seatReservation}
      
  mailer:
    mock: false
    from: ${MAIL_FROM}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    tls: ${MAIL_TLS}
    start-tls: ${MAIL_START_TLS}

  hibernate-orm:
    schema-management:
      strategy: drop-and-create

jwt:
  cookie:
    secure: false

email:  
  frontend-base-url: http://localhost:3000