name: frontend.yml
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "**/*.md" ]
    tags:
      - "v*.*"
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "**/*.md" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nextjs-build:
    name: nextjs build
    runs-on: "ubuntu-24.04"

    env:
      NODE_VERSION: '22.18.x'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Maven Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: webapp/node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node_modules-${{ hashFiles('webapp/package.json', 'webapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache Next.js build
        id: nextjs-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/webapp/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('webapp/package-lock.json') }}-${{ hashFiles('webapp/**/*.js', 'webapp/**/*.jsx', 'webapp/**/*.ts', 'webapp/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('webapp/package-lock.json') }}-

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
              cd webapp
              npm ci

      - name: Run generate:api
        run: |
              cd webapp 
              npm run generate:api

      - name: Check for changes of api client
        run: git diff --exit-code -- webapp/api/

      - name: Run ESLint
        run: |
              cd webapp
              npm run lint:check

      - name: Run Prettier
        run: |
              cd webapp
              npm run format:check

      - name: Build static
        run: |
              cd webapp
              npm run build:static

      - name: Upload build static artifact
        uses: actions/upload-artifact@v5
        with:
          name: frontend-build-static
          path: webapp/out

      - name: Build standalone
        run: |
              cd webapp
              npm run build

      - name: Upload build standalone artifact
        uses: actions/upload-artifact@v5
        with:
          name: frontend-build-standalone
          include-hidden-files: true
          path: |
            webapp/.next/standalone
            webapp/.next/static
          if-no-files-found: error
          retention-days: 4

  frontend-docker:
    needs: nextjs-build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: frontend-build-standalone
      build-artifact-path: webapp/.next/
      docker-file-path: ./webapp/Dockerfile
      container-image-title: Frontend
      image-name: ${{ github.repository }}-frontend